<a href="https://colab.research.google.com/github/ShlokAsthana73/NNA/blob/main/Tensors_Practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

# Create a tensor of shape (3, 3) with random numbers between 0 and 1

In [ ]:
tf.random.set_seed(2)
t1 = tf.random.uniform(shape=(3, 3), minval=0, maxval=1)
print(f"First Tensor Created")
print(t1)

First Tensor Created
tf.Tensor(
[[0.14690244 0.46425676 0.22489977]
 [0.35288846 0.9857408  0.99910235]
 [0.5648881  0.16375077 0.9890269 ]], shape=(3, 3), dtype=float32)


# Perform basic tensor operations including matrix addition, multiplication, and transpose

In [ ]:
tf.random.set_seed(3)
t2 = tf.random.uniform(shape=(3, 3), minval=0, maxval=1)
print(f"Second Tensor Created")
print(t2)

Second Tensor Created
tf.Tensor(
[[0.13366318 0.5678531  0.4963317 ]
 [0.01686525 0.50454175 0.74873126]
 [0.13033688 0.33561492 0.6519277 ]], shape=(3, 3), dtype=float32)


In [ ]:
# Perform matrix addition
addition = tf.add(t1, t2)
print(f"Matrix Addition")
addition

Matrix Addition


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.28056562, 1.0321099 , 0.72123146],
       [0.36975372, 1.4902825 , 1.7478336 ],
       [0.695225  , 0.4993657 , 1.6409546 ]], dtype=float32)>

In [ ]:
# Perform matrix multiplication
multiplication = tf.matmul(t1, t2)
print(f"Matrix multiplication")
print(multiplication)

Matrix multiplication
tf.Tensor(
[[0.05677799 0.39313564 0.56713426]
 [0.19401285 1.0330498  1.5645472 ]
 [0.20717312 0.73532474 1.0477512 ]], shape=(3, 3), dtype=float32)


In [ ]:
# Transpose
transpose = tf.transpose(t1)
print(f"Transpose of First Tensor")
print(transpose)
transpose2 = tf.transpose(t2)
print(f"\nTranspose of Seoncd Tensor")
print(transpose2)

Transpose of First Tensor
tf.Tensor(
[[0.14690244 0.35288846 0.5648881 ]
 [0.46425676 0.9857408  0.16375077]
 [0.22489977 0.99910235 0.9890269 ]], shape=(3, 3), dtype=float32)

Transpose of Seoncd Tensor
tf.Tensor(
[[0.13366318 0.01686525 0.13033688]
 [0.5678531  0.50454175 0.33561492]
 [0.4963317  0.74873126 0.6519277 ]], shape=(3, 3), dtype=float32)


# Convert the resulting tensor into a NumPy array and then reshape it into a (1, 9) tensor.

In [ ]:
# Convert tensor to NumPy array
numpy = t1.numpy()
print(f"Numpy Created")
print(numpy)

Numpy Created
[[0.14690244 0.46425676 0.22489977]
 [0.35288846 0.9857408  0.99910235]
 [0.5648881  0.16375077 0.9890269 ]]


In [ ]:
# Reshape the NumPy array to (1, 9)
reshaped = numpy.reshape(1, 9)
print(f"Numpy reshaped")
print(reshaped)

Numpy reshaped
[[0.14690244 0.46425676 0.22489977 0.35288846 0.9857408  0.99910235
  0.5648881  0.16375077 0.9890269 ]]
